package manage

// Spoof tunnels are created like the other standalone engines (WireGuard/Packet/
// SSH): a separate [spoof] section. There are two roles — a client (local UDP
// pipe) and a server (remote forwarder) — and two helper operations exposed to
// the panel: a spoof tester (does a forged source IP actually get delivered?)
// and an IP-list expander for the scanner.

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
	"time"

	"github.com/mahdi-byte64/arange-tun/internal/app"
	"github.com/mahdi-byte64/arange-tun/internal/spoof"
)

// SpoofClientReq / SpoofServerReq mirror the [spoof] config for each role.
type SpoofClientReq struct {
	Name        string
	Key         string
	Transport   string
	SpoofIP     string
	PeerSpoofIP string
	Listen      string
	ServerIP    string
	ServerPort  int
	RecvPort    int
}

type SpoofServerReq struct {
	Name        string
	Key         string
	Transport   string
	SpoofIP     string
	PeerSpoofIP string
	ListenPort  int
	Forward     string
	ClientIP    string
	ClientPort  int
}

// CreateSpoofClient / UpdateSpoofClient write and (re)start a spoof client.
func CreateSpoofClient(req SpoofClientReq) (string, error) { return saveSpoofClient(req, false) }
func UpdateSpoofClient(req SpoofClientReq) (string, error) { return saveSpoofClient(req, true) }

func saveSpoofClient(req SpoofClientReq, edit bool) (string, error) {
	name := strings.TrimSpace(req.Name)
	if err := preSave(name, edit); err != nil {
		return "", err
	}
	req.Key = orRandomKey(req.Key)
	if req.SpoofIP == "" || req.PeerSpoofIP == "" || req.ServerIP == "" {
		return "", fmt.Errorf("spoof_ip, peer_spoof_ip and server_ip are required")
	}
	if req.Listen == "" || req.ServerPort < 1 || req.RecvPort < 1 {
		return "", fmt.Errorf("listen, server_port and recv_port are required")
	}
	toml := spoofRenderClient(req)
	if _, err := saveGeneratedTunnel(name, toml); err != nil {
		return "", err
	}
	return req.Key, nil
}

// CreateSpoofServer / UpdateSpoofServer write and (re)start a spoof server.
func CreateSpoofServer(req SpoofServerReq) (string, error) { return saveSpoofServer(req, false) }
func UpdateSpoofServer(req SpoofServerReq) (string, error) { return saveSpoofServer(req, true) }

func saveSpoofServer(req SpoofServerReq, edit bool) (string, error) {
	name := strings.TrimSpace(req.Name)
	if err := preSave(name, edit); err != nil {
		return "", err
	}
	req.Key = orRandomKey(req.Key)
	if req.SpoofIP == "" || req.PeerSpoofIP == "" || req.ClientIP == "" {
		return "", fmt.Errorf("spoof_ip, peer_spoof_ip and client_ip are required")
	}
	if req.ListenPort < 1 || req.ClientPort < 1 || req.Forward == "" {
		return "", fmt.Errorf("listen_port, client_port and forward are required")
	}
	toml := spoofRenderServer(req)
	if _, err := saveGeneratedTunnel(name, toml); err != nil {
		return "", err
	}
	return req.Key, nil
}

// preSave validates the name and existence for a create (must not exist) or an
// edit (must exist).
func preSave(name string, edit bool) error {
	if !validName(name) {
		return fmt.Errorf("invalid tunnel name %q — use letters, digits, dots, dashes (max 40)", name)
	}
	exists := fileExists(app.ConfigPath(name))
	if edit && !exists {
		return fmt.Errorf("no tunnel named %q to edit", name)
	}
	if !edit && exists {
		return fmt.Errorf("a tunnel named %q already exists", name)
	}
	return nil
}

func orRandomKey(key string) string {
	key = strings.TrimSpace(key)
	if key != "" {
		return key
	}
	buf := make([]byte, 32)
	_, _ = rand.Read(buf)
	return hex.EncodeToString(buf)
}

func spoofTransport(t string) string {
	switch strings.TrimSpace(t) {
	case "tcp", "icmp", "udp":
		return strings.TrimSpace(t)
	default:
		return "udp"
	}
}

func spoofRenderClient(req SpoofClientReq) string {
	var b strings.Builder
	b.WriteString("# Generated by arange-tun — do not edit while the service is running.\n")
	fmt.Fprintf(&b, "# name = %q\n\n", strings.TrimSpace(req.Name))
	b.WriteString("[spoof]\n")
	b.WriteString("role = \"client\"\n")
	fmt.Fprintf(&b, "key = %q\n", req.Key)
	fmt.Fprintf(&b, "transport = %q\n", spoofTransport(req.Transport))
	fmt.Fprintf(&b, "spoof_ip = %q\n", strings.TrimSpace(req.SpoofIP))
	fmt.Fprintf(&b, "peer_spoof_ip = %q\n", strings.TrimSpace(req.PeerSpoofIP))
	fmt.Fprintf(&b, "listen = %q\n", strings.TrimSpace(req.Listen))
	fmt.Fprintf(&b, "server_ip = %q\n", strings.TrimSpace(req.ServerIP))
	fmt.Fprintf(&b, "server_port = %d\n", req.ServerPort)
	fmt.Fprintf(&b, "recv_port = %d\n", req.RecvPort)
	return b.String()
}

func spoofRenderServer(req SpoofServerReq) string {
	var b strings.Builder
	b.WriteString("# Generated by arange-tun — do not edit while the service is running.\n")
	fmt.Fprintf(&b, "# name = %q\n\n", strings.TrimSpace(req.Name))
	b.WriteString("[spoof]\n")
	b.WriteString("role = \"server\"\n")
	fmt.Fprintf(&b, "key = %q\n", req.Key)
	fmt.Fprintf(&b, "transport = %q\n", spoofTransport(req.Transport))
	fmt.Fprintf(&b, "spoof_ip = %q\n", strings.TrimSpace(req.SpoofIP))
	fmt.Fprintf(&b, "peer_spoof_ip = %q\n", strings.TrimSpace(req.PeerSpoofIP))
	fmt.Fprintf(&b, "listen_port = %d\n", req.ListenPort)
	fmt.Fprintf(&b, "forward = %q\n", strings.TrimSpace(req.Forward))
	fmt.Fprintf(&b, "client_ip = %q\n", strings.TrimSpace(req.ClientIP))
	fmt.Fprintf(&b, "client_port = %d\n", req.ClientPort)
	return b.String()
}

// SpoofEdit is a spoof tunnel's config for the panel's edit form.
type SpoofEdit struct {
	Role        string `json:"role"`
	Key         string `json:"key"`
	Transport   string `json:"transport"`
	SpoofIP     string `json:"spoofIP"`
	PeerSpoofIP string `json:"peerSpoofIP"`
	Listen      string `json:"listen"`
	ServerIP    string `json:"serverIP"`
	ServerPort  int    `json:"serverPort"`
	RecvPort    int    `json:"recvPort"`
	ListenPort  int    `json:"listenPort"`
	Forward     string `json:"forward"`
	ClientIP    string `json:"clientIP"`
	ClientPort  int    `json:"clientPort"`
}

func SpoofForEdit(name string) (SpoofEdit, error) {
	cfg, err := LoadTunnelConfig(name)
	if err != nil {
		return SpoofEdit{}, err
	}
	s := cfg.Spoof
	if s.Role == "" {
		return SpoofEdit{}, fmt.Errorf("%q is not a spoof tunnel", name)
	}
	return SpoofEdit{
		Role: s.Role, Key: s.Key, Transport: s.Transport,
		SpoofIP: s.SpoofIP, PeerSpoofIP: s.PeerSpoofIP,
		Listen: s.Listen, ServerIP: s.ServerIP, ServerPort: s.ServerPort, RecvPort: s.RecvPort,
		ListenPort: s.ListenPort, Forward: s.Forward, ClientIP: s.ClientIP, ClientPort: s.ClientPort,
	}, nil
}

// SpoofList returns just the spoof tunnels, for the dedicated panel.
func SpoofList() []Tunnel {
	var out []Tunnel
	for _, t := range List() {
		if t.Transport == "spoof" {
			out = append(out, t)
		}
	}
	return out
}

// ---- Tester + scanner (thin wrappers over the engine) ----

// SpoofReceive listens for probe packets for `seconds` and returns, per forged
// source IP, how many arrived. Run it on the peer, then send from the other box.
func SpoofReceive(port int, transport string, seconds int) (map[string]int, error) {
	if port < 1 || port > 65535 {
		return nil, fmt.Errorf("invalid port %d", port)
	}
	if seconds < 1 {
		seconds = 10
	}
	if seconds > 120 {
		seconds = 120
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(seconds)*time.Second)
	defer cancel()
	return spoof.RunReceiver(ctx, "", port, transport)
}

// SpoofSend forges `count` probes from each IP toward the peer's real IP:port.
func SpoofSend(peerRealIP string, port int, transport string, ips []string, count int) error {
	if len(ips) == 0 {
		return fmt.Errorf("no spoof IPs to test")
	}
	if count < 1 {
		count = 20
	}
	if count > 200 {
		count = 200
	}
	probes := make([]spoof.TestProbe, 0, len(ips))
	for _, ip := range ips {
		probes = append(probes, spoof.TestProbe{SpoofIP: ip, Count: count})
	}
	return spoof.SendProbes("", peerRealIP, port, transport, probes)
}

// SpoofExpandIPs turns a single/range/CIDR spec into concrete IPs for the scanner.
func SpoofExpandIPs(spec string, max int) ([]string, error) {
	return spoof.ExpandIPs(spec, max)
}
