package manage

// SSH tunnels are created like WireGuard/Packet ones: a separate engine with its
// own [ssh] section. There is only one role — a client that dials an SSH server
// abroad (host/user/password) and exposes a local SOCKS5 proxy through it.

import (
	"fmt"
	"strings"

	"github.com/mahdi-byte64/arange-tun/internal/app"
)

// CreateSSHClient starts an SSH egress client: it connects to host:port as user
// and opens a SOCKS5 proxy on socksPort.
func CreateSSHClient(name, host string, port int, user, password, socksBind string, socksPort int) error {
	name = strings.TrimSpace(name)
	if !validName(name) {
		return fmt.Errorf("invalid tunnel name %q — use letters, digits, dots, dashes (max 40)", name)
	}
	if _, ok := Find(name); ok {
		return fmt.Errorf("a tunnel named %q already exists", name)
	}
	if err := validateSSH(host, port, user, socksPort); err != nil {
		return err
	}
	toml := sshRenderClient(name, strings.TrimSpace(host), sshPort(port), strings.TrimSpace(user), password, sshBind(socksBind), socksPort)
	_, err := saveGeneratedTunnel(name, toml)
	return err
}

// SSHEdit is an SSH tunnel's editable config for the panel's form.
type SSHEdit struct {
	Host      string `json:"host"`
	Port      int    `json:"port"`
	User      string `json:"user"`
	Password  string `json:"password"`
	SocksBind string `json:"socksBind"`
	SocksPort int    `json:"socksPort"`
}

// SSHForEdit loads an SSH tunnel's config so the panel can prefill its form.
func SSHForEdit(name string) (SSHEdit, error) {
	cfg, err := LoadTunnelConfig(name)
	if err != nil {
		return SSHEdit{}, err
	}
	s := cfg.SSH
	if s.Role == "" {
		return SSHEdit{}, fmt.Errorf("%q is not an SSH tunnel", name)
	}
	return SSHEdit{
		Host:      s.Host,
		Port:      s.Port,
		User:      s.User,
		Password:  s.Password,
		SocksBind: s.SocksBind,
		SocksPort: s.SocksPort,
	}, nil
}

// UpdateSSHClient overwrites an existing SSH tunnel and restarts it. An empty
// password keeps the current one, so editing other fields does not require
// re-typing it.
func UpdateSSHClient(name, host string, port int, user, password, socksBind string, socksPort int) error {
	name = strings.TrimSpace(name)
	if !fileExists(app.ConfigPath(name)) {
		return fmt.Errorf("no tunnel named %q to edit", name)
	}
	if err := validateSSH(host, port, user, socksPort); err != nil {
		return err
	}
	if strings.TrimSpace(password) == "" {
		if cfg, err := LoadTunnelConfig(name); err == nil {
			password = cfg.SSH.Password
		}
	}
	toml := sshRenderClient(name, strings.TrimSpace(host), sshPort(port), strings.TrimSpace(user), password, sshBind(socksBind), socksPort)
	_, err := saveGeneratedTunnel(name, toml)
	return err
}

func validateSSH(host string, port int, user string, socksPort int) error {
	if strings.TrimSpace(host) == "" {
		return fmt.Errorf("the server IP or domain is required")
	}
	if port != 0 && (port < 1 || port > 65535) {
		return fmt.Errorf("invalid SSH port %d", port)
	}
	if strings.TrimSpace(user) == "" {
		return fmt.Errorf("the SSH username is required")
	}
	if socksPort < 1 || socksPort > 65535 {
		return fmt.Errorf("invalid SOCKS5 port %d", socksPort)
	}
	return nil
}

func sshPort(p int) int {
	if p <= 0 {
		return 22
	}
	return p
}

func sshBind(b string) string {
	b = strings.TrimSpace(b)
	if b == "" {
		return "127.0.0.1"
	}
	return b
}

func sshRenderClient(name, host string, port int, user, password, socksBind string, socksPort int) string {
	var b strings.Builder
	b.WriteString("# Generated by arange-tun — do not edit while the service is running.\n")
	fmt.Fprintf(&b, "# name = %q\n\n", name)
	b.WriteString("[ssh]\n")
	b.WriteString("role = \"client\"\n")
	fmt.Fprintf(&b, "host = %q\n", host)
	fmt.Fprintf(&b, "port = %d\n", port)
	fmt.Fprintf(&b, "user = %q\n", user)
	fmt.Fprintf(&b, "password = %q\n", password)
	fmt.Fprintf(&b, "socks_bind = %q\n", socksBind)
	fmt.Fprintf(&b, "socks_port = %d\n", socksPort)
	return b.String()
}
